### ISSUE TITLE
Docker Container not available

### ISSUE THREAD

**Issue by TAC911** [straumat/blockchain2graph#105]
Hi,

executing `docker-compose up -d` as described in wiki throws error

```
Pulling app (oakinvest/blockchain2graph:latest)...
ERROR: repository oakinvest/blockchain2graph not found: does not exist or no pull access
```

Not sure if the container was removed and is not available anymore (or accesses are managed).

Best,
Tac

**Comment by jgoncalves16** [comment]
Hi,
This image is build locally with maven. Did you launch following command before ?

maven install docker:build

Best,
Juan

**Comment by Amplicade** [comment]
Hi,
thank you. I'm doing this right now - how long is it supposed to run? It seems it's processing all blocks (I'm currently at Block 000013856 after 1h) and I see log entries like:
`java.lang.RuntimeException: Impossible to find the original output transaction TRANSACTION-ID`  
I'm not sure if this is expected or if I'm doing something wrong here (in that case I'm sorry for bothering..). 

Cheers,
Tac

**Comment by straumat** [comment]
Hi. Please use the 0.4 release or tag. Not the one currently  in development. There is still a problem with neo4j a des multi thread I did not solve. 
0.4 is slower because it's multi thread but it works 😀

**Comment by TAC911** [comment]
Thanks @straumat that helped. But the build (`maven install docker:build`) is now failing with 
`Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (default-cli) on project blockchain2graph: Exception caught: lstat blockchain2graph.jar: no such file or directory -> [Help 1]`
Running `maven clean package` was successful. I'm kind of new to maven so if there is anything I'm missing, please bear with me.

Cheers,
Tac

**Comment by TAC911** [comment]
If you change the `<packaging>war</packaging>` to `<packaging>jar</packaging>?` in `pom.xml` the build succeeds.
