### ISSUE TITLE
Replacing caffeine cache with a home made buffer

### ISSUE THREAD

**Issue by straumat** [straumat/blockchain2graph#126]

**Comment by ben-manes** [comment]
Can you please explain the motivation for this change? I am sure it is valid, as the library can't be ideal for all purposes. I would appreciate the feedback to better understand the deficiencies.

**Comment by straumat** [comment]
In fact, my need was not to have a cache on loadead block from bitcoind. 
To really improve performances, i need to read blocks ahead of their insertion in neo4j.
So i developped a simple Set and a Scheduler that read 100 blocks ahead of the import process. This way, when there is an import of a block, i'ts already in the set
