### ISSUE TITLE
Cant browse Graph in Neo4j

### ISSUE THREAD

**Issue by loewensteinph** [straumat/blockchain2graph#157]
Im not sure if my neo4j config is setup correct. Currently the config

/etc/neo4j/neo4j.conf
dbms.directories.data=/var/lib/neo4j/data

points to "/var/lib/neo4j/data"

Whereas b2g seems to store stuff in

/var/lib/tomcat8/target/neo4j-run

A bunch of transaction files are beeing created.
 
neostore.transaction.db.74

Do i need to reconfigure 

dbms.directories.data=/var/lib/neo4j/data

to

/var/lib/tomcat8/target/neo4j-run ?

Currently the process is still running 

163.381 / 486.122

Do i have to wait untill its finished initially?

**Comment by straumat** [comment]
Hello. It seems you are running blockchain2graph directly from the source. When you do that, it desn't use the neo4J server but an embedded release. Here is the documentation for installing it and use the server neo4j insrance  [https://github.com/straumat/blockchain2graph/wiki/installation_1.3](url)

**Comment by loewensteinph** [comment]
I followed the 1.3 guide. Seems like I've to adjust 

spring.data.neo4j.uri : Connection URI to connect to the neo4j database (example :bolt://neo4j:b2g@localhost)

How can I specify a password? Within the connection string?

**Comment by straumat** [comment]
Yes the passsword is _b2g_ in the sample you provide (bolt://neo4j:b2g@localhost)
