### ISSUE TITLE
No response from bitcoind for block n°000000009

### ISSUE THREAD

**Issue by Lyle-liang** [straumat/blockchain2graph#209]
<img width="939" alt="image" src="https://user-images.githubusercontent.com/14850448/40965011-2a7b07d0-68df-11e8-87a8-cd1087780737.png">

I do not use docker. all components is installed. so can you give me any help?

**Comment by Lyle-liang** [comment]
It's OK.  but  I get another ERROR...
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/14850448/40979636-e8cfe092-6908-11e8-9bed-6ff21b8b6f90.png">

PS:
1. Can I use it always?
2. Can the server be available?
3. Does it synchronize data in real time?

**Comment by Lyle-liang** [comment]
ERROR is still exist..., can you any solution?
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/14850448/40981012-7ae6d64a-690c-11e8-9976-2a39d20d265f.png">

**Comment by straumat** [comment]
Can you try to reset the database and the process please ?

**Comment by Lyle-liang** [comment]
all env is new, but ERROR is appear。。
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/14850448/41012581-c3fb8c3c-6974-11e8-95ad-f10f682c497d.png">

**Comment by straumat** [comment]
Can you give me the release of neo4j : `neo4j version`
can you also tell me which release of blockchain2graph you downloaded ?

Also try to reset the database : 
```
service tomcat8 stop;service neo4j stop
rm -rdf /var/lib/neo4j/data/
service neo4j start
sleep 30s
curl -H "Content-Type: application/json" -X POST -d '{"password":"YOUR_NEW_PASSWORD"}' -u neo4j:neo4j http://localhost:7474/user/neo4j/password
service tomcat8 start
```

_note : change YOUR_NEW_PASSWORD by your password._

**Comment by Lyle-liang** [comment]
neo4j:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/14850448/41080625-066c3b6c-6a5a-11e8-98d8-c37b5e96f5e6.png">

blockchain2graph: I try  version 2.2 and 2.1

**Comment by straumat** [comment]
Please install another release of neo4j : `apt-get update;apt-get -y install neo4j=3.3.4;apt-mark hold neo4j`

**Comment by Lyle-liang** [comment]
I install neo4j 3.3.4,but no..
<img width="835" alt="image" src="https://user-images.githubusercontent.com/14850448/41143925-aee7db9c-6b2d-11e8-9e46-9245defe83dd.png">
<img width="243" alt="image" src="https://user-images.githubusercontent.com/14850448/41143945-bec8155e-6b2d-11e8-9762-fb176fc66917.png">

**Comment by straumat** [comment]
Ok, do you think i can access your server to solve the problem ?

**Comment by Lyle-liang** [comment]
because of security,  I think it is not ok...what is reason with it? Can I do something?

**Comment by straumat** [comment]
Honestly, i don't see why you have thoses messages. I don't succeed to reproduce. Did you follow exactly the instruction guide ? I really don't see why you have those messages :(

**Comment by Lyle-liang** [comment]
EveryThing is new and follow the steps :https://github.com/straumat/blockchain2graph/wiki/installation_2.2 , but I meet the same Error.
can I get the graph.db from you?

**Comment by straumat** [comment]
You can get the 70 000 first block here : `http://oak-invest.com/download/neo4j-data-sample.zip`
Can you check your tomcat release too ? Thanks

**Comment by Lyle-liang** [comment]
yeah, I get the zip and use tomcat8. Thanks

**Comment by straumat** [comment]
I dont have à full database yet. sort

**Comment by Lyle-liang** [comment]
Oh...Thanks.
