### ISSUE TITLE
docker does not work 

### ISSUE THREAD

**Issue by ElSeidy** [straumat/blockchain2graph#221]
I keep on getting the same error whenever I use docker.
**Describe the bug**
Continue with the new image? [yN]y
Pulling blockchain2graph-bitcoin (straumat/blockchain2graph-bitcoin:2.3-SNAPSHOT)...
ERROR: pull access denied for straumat/blockchain2graph-bitcoin, repository does not exist or may require 'docker login'

**To Reproduce**
sudo docker-compose up

**Desktop (please complete the following information):**
 - OSX

**Comment by straumat** [comment]
Hello, sorry i forget to update the docker-compose file. Can you try with this one please ? [https://gist.github.com/straumat/54edc240554f84c71b81a8d926b8f5be](https://gist.github.com/straumat/54edc240554f84c71b81a8d926b8f5be)

**Comment by straumat** [comment]
Is it ok now ?
