### ISSUE TITLE
the num of Blocks in bitcoin core is wrong?

### ISSUE THREAD

**Issue by Lyle-liang** [straumat/blockchain2graph#222]
I run it with docker and work.but the num of Blocks is always 100 012。 Why？

I use your docker-compose-blockchain2graph-bitcoin-neo4j.yml and no change.

![image](https://user-images.githubusercontent.com/14850448/44375718-a24c0a00-a527-11e8-87db-417e700db00c.png)

**Comment by straumat** [comment]
Hello Lyle-liang, in fact, when the block count reach more than 100 000 blocks, a blockcount cache is activated. Blockchain2graph, will keep the result for 10 minutes and will call again the blockcount. So if you waited less than 10 minutes, it's normal. If not, there may be a bug

**Comment by Lyle-liang** [comment]
Hi, the block count keep 100012 for more 6 hours and don't change. there may be a bug. I find bitcoin core server is ok, get block count is right by api. And Does this bug affect BTC data import? Thanks.

**Comment by Lyle-liang** [comment]
@straumat I install a new one and meet the message. like this:
![image](https://user-images.githubusercontent.com/14850448/44437571-58c5f280-a5ed-11e8-993d-fda1c08b7eea.png)

**Comment by straumat** [comment]
I think i found the mistake. I pushed a new release. I wasn't able to fully test the fix.
The CI and the imabge build will occur in the next 30 minutes.

You can try yourself in 30 minutes and you have to change your docker compose file to put :  
```
blockchain2graph-bitcoin-neo4j:
    image: straumat/blockchain2graph-bitcoin-neo4j:3.1-SNAPSHOT
```

**Comment by Lyle-liang** [comment]
Thanks very much.

**Comment by Lyle-liang** [comment]
@straumat I am back. The 3.1-SNAPSHOT can run, but don't work well. Can you help me?
![image](https://user-images.githubusercontent.com/14850448/44500040-38fc0080-a6b9-11e8-966a-ebeb21dc5b0e.png)

the block num is right in bitcoin core.
![image](https://user-images.githubusercontent.com/14850448/44500141-b6c00c00-a6b9-11e8-8e6a-a4e0091c2fe1.png)

**Comment by straumat** [comment]
Ok, I found where it comes from and I made a test, it works now. The 3.1-SNAPSHOT image has been updated.

**Comment by Lyle-liang** [comment]
@straumat Thanks, I will use The 3.1-SNAPSHOT image.

**Comment by Lyle-liang** [comment]
@straumat I am back. I try the 3.1-SNAPSHOT image and encounter the same problem。

![image](https://user-images.githubusercontent.com/14850448/44759840-d9956900-ab6e-11e8-9a4a-5cf52f64225a.png)

the error message is the same as before and the num of Blocks in neo4j don't change. 

I hope you can help me, Thanks.

**Comment by straumat** [comment]
Can you restart please ? It's strange as this message often appears when bitcoin core is overloaded but the priocess usually continues.

**Comment by Lyle-liang** [comment]
I have restarted and work, but the error always exist. transaction id change fast. like this:
![image](https://user-images.githubusercontent.com/14850448/44781277-89da9000-abb6-11e8-8ae0-27031206578e.png)

**Comment by straumat** [comment]
Ok, can you open a new issue please ? I'm trying to reproduce it.

**Comment by Lyle-liang** [comment]
Ok, thanks.
