### ISSUE TITLE
Aggregate UTXOs based on price when they were last used

### ISSUE THREAD

**Issue by Muggsie** [straumat/blockchain2graph#225]
**Is your feature request related to a problem? Please describe.**
I am exploring alternative methods of measuring how much wealth is stored in a given cryptoasset. I want to separate active and in-active units (Forever lost coins)

**Describe the solution you'd like**

Aggregate UTXOs (unspent transactional outputs) based on price when they were last used in a transaction. 

Must weight each UTXO by the amount of Bitcoin it contains

I think a cumulative sum chart would be the best

**Describe alternatives you've considered**

**Additional context**

**Comment by straumat** [comment]
We don't retrieve pricing but you can develop a batch to update Bitcointransaction output
