### ISSUE TITLE
417317 block processing error

### ISSUE THREAD

**Issue by edward3132** [straumat/blockchain2graph#226]
![image](https://user-images.githubusercontent.com/43660163/47329577-37968680-d6b0-11e8-9505-00327e3563d7.png)

An error occurred during 417317 block processing
The error message is "Incorrect result size: expected at most 1"

**Comment by straumat** [comment]
Hi, can you provide the error in the logs ? I need to see the Java exception detals

**Comment by edward3132** [comment]
417317block_err.log
<https://drive.google.com/file/d/1cRFurwaSRqRisvkBy3-y4gEHZZqYWOV_/view?usp=drive_web>

2018년 10월 23일 (화) 오후 11:54, Stéphane Traumat <notifications@github.com>님이
작성:

**Comment by straumat** [comment]
Very strange. It seems some data are missing but it is suposed to be impossible as every block is treated within a transaction. Can you try with the snapshot release ?

**Comment by edward3132** [comment]
I do not know what "Can you try with the snapshot release ?" is doing.

나의 iPhone에서 보냄

2018. 10. 27. 오전 5:02, Stéphane Traumat <notifications@github.com> 작성:

**Comment by straumat** [comment]
What release of blockchain2graph are you using ? Are you using docker ?
