### ISSUE TITLE
About Transaction detail for each address/block?

### ISSUE THREAD

**Issue by mmanishh** [straumat/blockchain2graph#237]
Hi, 

I wanted to know how did you extract transaction details for each address / block ? Did you itereate from the genesis block and get transaction detail from the very first ?

**Comment by straumat** [comment]
Hello, yes, i'm starting at block 1 andI I call Bitcoind core to retrieve all transactions data. Then I process the next block.

**Comment by mmanishh** [comment]
How did u retrieve all transactions?

**Comment by mmanishh** [comment]
Hi , Just figured out that you retrieve block hash of genesis block , then transaction ids and then detail of transactions. Many thanks !!
