### ISSUE TITLE
Problem with docker compose

### ISSUE THREAD

**Issue by imadmoussa1** [straumat/blockchain2graph#294]
I am using the latest docker-compose version, and I have this error in docker-compose log for blockchain2graph-bitcoin-neo4j_1 :
"Error getting the number of blocks : I/O error on post request for http://bitcoin-core:8332: Connection refused; nested exception is java.net.ConnectionException: Connection refused"

**Comment by straumat** [comment]
Ok, from the 0.18.0 release notes : 
> The rpcallowip option can no longer be used to automatically listen on all network interfaces. Instead, the rpcbind parameter must be used to specify the IP addresses to listen on. Listening for RPC commands over a public network connection is insecure and should be disabled, so a warning is now printed if a user selects such a configuration. If you need to expose RPC in order to use a tool like Docker, ensure you only bind RPC to your localhost, e.g. docker run [...] -p 127.0.0.1:8332:8332 (this is an extra :8332 over the normal Docker port specification).

So I should find a way to bind bitcoind to the docker ip address and i don't know how for the moment.

Is it ok for you to use bitcoin 0.17.0 ? This docker-compose works. I tried it.
[https://gist.github.com/straumat/54edc240554f84c71b81a8d926b8f5be/9892955f09806ea08f7fe128e37f286bf8c8ea07](https://gist.github.com/straumat/54edc240554f84c71b81a8d926b8f5be/9892955f09806ea08f7fe128e37f286bf8c8ea07)

**Comment by imadmoussa1** [comment]
Thank you. I used bitcoin 0.17.0 and it's working.
I will work to bind the bitcoin node to the docker ip address.

**Comment by straumat** [comment]
Good. Be carefull, bitcoin 0.18 is much more faster than 0.17.0

**Comment by straumat** [comment]
It works now : https://gist.github.com/straumat/54edc240554f84c71b81a8d926b8f5be
thanks to https://github.com/straumat/blockchain2graph/issues/316
