### ISSUE TITLE
Advise needed: Neo4J crashed during import

### ISSUE THREAD

**Issue by arisjr** [straumat/blockchain2graph#304]
I have a blockchain2graph docker environment. 

At the end of import, it was missing only a few thousand blocks, neo4j crashed due a diskfull problem. Database was with 2.5 TB. 

After I added more space on the target database drive, neo4j started and replayed some transactions that wasn't committed, but a transaction file was corrupt, than it wasn't inserted. but things so far seemed to start ok. 

Now I'm stuck with an error: "An error occurred while processing block : Origin transaction not found e83f0ef6f0c01a77b5200b9c5e4d62552deecae69dac60b602c77f575f5fea71 / 1"

So I need an expert advise: What is the best action to do in this scenario?

Best regards,
--arisjr

**Comment by straumat** [comment]
I'm afraid you have to start all over again. There is a [bug in Neo4j : Neo4J gets corrupted when runs out of disk space, no way to fix it](https://github.com/neo4j/neo4j/issues/11573).
In the issue, they give some informations, take a look at it but i'm scared there is nothing yiou can do.
