### ISSUE TITLE
Wasnt able to get the systemd to run for blockchain2graph-bitcoin-neo4j.service 

### ISSUE THREAD

**Issue by chankongching** [straumat/blockchain2graph#307]
**Describe the bug**
The SuccessExitStatus=143 is not working

**To Reproduce**
Follow the procedure to create the blockchain2graph-bitcoin-neo4j systemd service

**Expected behavior**
Service failing to start

**Screenshots**
no screen shot

**Desktop (please complete the following information):**
 - OS: debian stretch

**Additional context**
Version 3.0

eventually i fixed by rewriting the service file
`[Install]
WantedBy=multi-user.target

[Unit]
Description=Blockchain2graph-bitcoin-neo4j
After=syslog.target

[Service]
ExecStart=/bin/bash -c "export SPRING_DATA_NEO4J_URI="bolt://neo4j:MYPASSWORD@localhost";export BITCOINCORE_HOSTNAME=18.162.116.82;export BITCOINCORE_PORT=8333;export BITCOINCORE_USERNAME=bitcoinrpc;export BITCOINCORE_PASSWORD=neo4j:MYPASSWORD;exec /usr/bin/java -jar /var/blockchain2graph/blockchain2graph-bitcoin-neo4j.jar || true"

[Install]
WantedBy=multi-user.target`

**Comment by straumat** [comment]
Thanks a lot ! I will fix the documentation in the next release.

**Comment by straumat** [comment]
Hello, I updated the documentation and the releases (debian 10, neo4j 3.5....) and it works with my script : https://github.com/straumat/blockchain2graph/wiki/installation_3.1_bitcoin_neo4j
