### ISSUE TITLE
A timer for completion would be nice

### ISSUE THREAD

**Issue by nikhilh-20** [straumat/blockchain2graph#317]
It would be nice to have a timer to understand how long it would take for all the blocks to be imported into neo4j. I have the following status:

![image](https://user-images.githubusercontent.com/9674215/65274802-2e957b80-daf2-11e9-9d8c-7e9652a8c06a.png)

and I don't know how long I would have to wait for all blocks to be processed. In this case, I don't even know if the process is actually proceeding or if it's hung (how do I determine this?) The first 4446 blocks were imported really quickly for some reason.

**Comment by straumat** [comment]
Thanks. I will work on it
