### ISSUE TITLE
Running `blockchain2graph` with `bitcoin-core` service offline

### ISSUE THREAD

**Issue by nikhilh-20** [straumat/blockchain2graph#318]
Is it possible to run `blockchain2graph` service without requiring it to connect to `bitcoin-core`? I was looking to use the downloaded blockchain instead of updating it in real time.

**Comment by straumat** [comment]
Nope sorry. We only make RPC calls

Le ven. 20 sept. 2019 à 16:47, Nikhil Hegde <notifications@github.com> a
écrit :
