### ISSUE TITLE
Parsing data to neo4j is too slow

### ISSUE THREAD

**Issue by AndyShenAS** [straumat/blockchain2graph#377]
I'm running this project with the docker on GCP(8 cores, 32G memory, 1T SSD).

But the speed of importing data into the neo4j is really unbearably slow.
![image](https://user-images.githubusercontent.com/16560838/71305574-9a50f280-2419-11ea-9b40-96eb9dc14720.png)

Can you provide an image of the parsed neo4j data? Either AWS or GCP.
Thanks a lot!

**Comment by straumat** [comment]
Hello, i'm sorry but I don't have an image of that :( i tried to make one but it takes 4T and I did not find any place to store it.
