### ISSUE TITLE
Error mapping GraphModel to instance of com.oakinvest.b2g.domain.BitcoinTransactionOutput

### ISSUE THREAD

**Issue by fbruzzaniti** [straumat/blockchain2graph#594]
Receiving the error "An error occurred while processing block : Error mapping GraphModel to instance of com.oakinvest.b2g.domain.BitcoinTransactionOutput; nested exception is org.neo4j.ogm.exception.core.MappingException: Error mapping GraphModel to instance of com.oakinvest.b2g.domain.BitcoinTransactionOutput".  Previously I was getting "Caused by: Error mapping GraphModel" with version 3.2. Downgraded to 3.1 seemed to fix the error now am gettiong this error have tried with version 3.0 as well same issue. Am running on Ubuntu 20.04, openjdk 11.0.8.

**Comment by straumat** [comment]
@fbruzzaniti hello, strange you still have this error with the previous release ? in which block number ?
Did you drop the database before trying another release ?

**Comment by fbruzzaniti** [comment]
Hi!  I didn't drop the databases before trying the different releases perhaps that is my issue. I'll drop the db and try again with 3.1

**Comment by fbruzzaniti** [comment]
<img width="1244" alt="Screen Shot 2020-08-20 at 11 46 12 pm" src="https://user-images.githubusercontent.com/3473383/90783616-7b578700-e33f-11ea-97b8-eeba74923aca.png">

Stuck on this block using 3.1

**Comment by straumat** [comment]
Can you make a try with the docker images and blockchain2graph 3.0? 

Here is my docker-compose.yml file : [https://gist.github.com/straumat/54edc240554f84c71b81a8d926b8f5be](https://gist.github.com/straumat/54edc240554f84c71b81a8d926b8f5be).

**Comment by straumat** [comment]
Works here with docker

![Screenshot (1)](https://user-images.githubusercontent.com/536498/90790268-28161200-e308-11ea-9d0b-f63ac3211b28.png)

**Comment by fbruzzaniti** [comment]
Works error free via the Docker compose file, thanks!

**Comment by fbruzzaniti** [comment]
FYI Receiving this error but seems to be processing:

Error getting the transaction 7a6e0e1498d97a1d5f02de98772aa6e46fa1df9dc0e34a7a55ca3cea96b7e7c2 : Could not extract response: no suitable HttpMessageConverter found for response type [class com.oakinvest.b2g.dto.bitcoin.core.getrawtransaction.GetRawTransactionResponse] and content type [text/html;charset=ISO-8859-1]

**Comment by straumat** [comment]
Yes, from times to times, we don't get a reply from bitcoin core but it will retry and finally works
