### ISSUE TITLE
Error: Could not extract response: no suitable HttpMessageConverter found

### ISSUE THREAD

**Issue by fbruzzaniti** [straumat/blockchain2graph#595]
Receiving this error but appears to be processing:
Error getting the transaction 87fb8b37fa34284f6e6e41bd06e64bdad9448a84c71937fe5b719649944268e6 : Could not extract response: no suitable HttpMessageConverter found for response type [class com.oakinvest.b2g.dto.bitcoin.core.getrawtransaction.GetRawTransactionResponse] and content type [text/html;charset=ISO-8859-1]

Also noticed this error from bitcond:
2020-08-21T01:57:41Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting

I thought they might be related, currently using the 3.0 Docker Compose file.

**Comment by fbruzzaniti** [comment]
Added -rpcworkqueue=100 to Docker command as an experiment, seems to have improved performance and the error has gone, here is the full command for reference: 

'-server=1' '-rest=1' '-rpcuser=bitcoinrpc' '-rpcworkqueue=100' '-rpcpassword=JRkDy3tgCYdmCEqY1VdfdfhTswiRva' '-txindex=1' '-rpcallowip=0.0.0.0/0' '-rpcbind=127.0.0.1' '-rpcbind=bitcoin-core' '-rpcallowip=::/0'

**Comment by straumat** [comment]
Thanks a lot, i will add this parameter.
