### ISSUE TITLE
Started by own bitcoin-core and setup neo4j but see no blocks

### ISSUE THREAD

**Issue by teachmlrepo** [straumat/blockchain2graph#610]
Hi 

I am able to start application when I hit localhost:8080
I see Blocks in bitcoincore: n/a
         Blocks in neo4j : na all are shown as n/a
          no blocks to process 

But I see that my bitcoin core is active and running
{
  "chain": "main",
  "blocks": 647527,
  "headers": 647527,
  "bestblockhash": "0000000000000000000651c87d7b2ba83357bd402c2d5f851d32e3928e5c60a3",
  "difficulty": 17345997805929.09,
  "mediantime": 1599687201,
  "verificationprogress": 0.9999934442831205,
  "initialblockdownload": false,
  "chainwork": "00000000000000000000000000000000000000001350ba51193268e8cc99d258",
  "size_on_disk": 338841263037,
  "pruned": false,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 227931
    },
    "bip66": {
      "type": "buried",
      "active": true,
      "height": 363725
    },
    "bip65": {
      "type": "buried",
      "active": true,
      "height": 388381
    },
    "csv": {
      "type": "buried",
      "active": true,
      "height": 419328
    },
    "segwit": {
      "type": "buried",
      "active": true,
      "height": 481824
    }
  },
  "warnings": ""
}

I am little confused about the settings here about the service settings, here, 
bitcoincore username is my username and my password,
I have no idea about SPRING_DATA_NEO4J_URI i have kept the same as default.

Can you please let me know if there is any log apart from syslog to check for whats hapenning, Else can you please let meknow what is hapenning and how to resolve this 

Thanks

[Unit]
Description=Blockchain2graph-bitcoin-neo4j
After=syslog.target

[Service]
Environment="SPRING_DATA_NEO4J_URI=bolt://neo4j:b2g135!@localhost"
Environment="BITCOINCORE_HOSTNAME=localhost"
Environment="BITCOINCORE_PORT=8332"
Environment="BITCOINCORE_USERNAME=**bitcoinrpc**" : 
Environment="BITCOINCORE_PASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva"
ExecStart=/usr/bin/java -jar /var/blockchain2graph/blockchain2graph-bitcoin-neo4j.jar SuccessExitStatus=143

[Install]
WantedBy=multi-user.target

**Comment by straumat** [comment]
Hello, which release are you using ? I think you should try with the 3.0 release

**Comment by teachmlrepo** [comment]
Thanks mate,
I am able to run docker compose and application is up and running now,

Many Thanks for good code and application
