### ISSUE TITLE
Two mvn test crashes

### ISSUE THREAD

**Issue by straumat** [straumat/blockchain2graph#79]

**Comment by jgoncalves16** [comment]
What was the problem ?

**Comment by straumat** [comment]
Loading a node entity only retrieve the objects around the loaded object.
Adding In the tests :
`
a1.getDeposits().stream().forEach(o -> o = btor.findOne(o.getId()));
a1.getWithdrawals().stream().forEach(i -> i = btir.findOne(i.getId()));
`
force loading of transactions data.

Still, i have to discover how come the objects are fully loaded after insert. It seems that there is a kind of cache in neo4J or SDN.

**Comment by jgoncalves16** [comment]
Thanks.
For cache, maybe there : http://stackoverflow.com/questions/35207954/spring-data-neo4j-4returning-cached-results

**Comment by straumat** [comment]
Yes :) that's exactly what I was reading. Seem session.clear does not work the way I expected
